[package]
name = "todo_list"
version = "0.1.0"
authors = ["alalfakawma <alalfakawma@live.com>"]
edition = "2018"
description = "Just a simple Ncurses Todo List"
license = MIT

[dependencies]
ncurses = "5.86.0"
